version: 2
dist: releases
snapshot:
  version_template: '{{ .Summary }}'
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    binary: nanobot
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
universal_binaries:
  - id: mac
    ids:
      - default
    replace: true
archives:
  - formats: ['tar.gz']
    ids:
      - default
      - mac
    name_template: >-
      {{ .ProjectName }}_ {{- .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: nanobot-ai
    name: nanobot
  prerelease: auto
brews:
  - name: nanobot
    description: 'Nanobot cli'
    install: |
      bin.install "nanobot"
    homepage: 'https://nanobot.ai'
    skip_upload: false
    directory: Formula
    repository:
      owner: nanobot-ai
      name: homebrew-tap
      token: "{{ .Env.GHCR_TOKEN }}"
